### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by 0999312** [0999312/Project-ZeroOne#1]
代码问题：
————————————————————————————————
- [x] 旧版基岩版模型性能问题很大，需要处理
- [x] 基岩版模型导致护甲模型错位（ModelArmorJson类处理护甲模型）
- [ ] Rise Key / Riser / Driver —— 骑士系统
- [ ] AI辅助设备（Humagear Module/Zaiaspec）
- [ ] “卫星”系统：给玩家提供一个“卫星”的Capability并且通过调用来实现与卫星的“连接”
- [ ] 各类机械方块：发电机——粉碎机——回收机——提取机——物质合成机——物质打印机 等
- [ ] 各类武器以及必杀
- [ ] Rise Phone / Rise Hopper
————————————————————————————————
模型问题：
- [ ] Rise Phone / Rise Hopper
- [ ] 各类皮套：主骑（0/100%）、副骑（0/100%）、千骑（0/1000%）、杂兵（0/100%），具体需求在群内说明。
- [ ] 各类RiseKey：普通Key（模型完成，材质数量大）、千骑Key、02 Key、Ark Key
- [ ] 各类武器：公文包（0/3）、千骑剑、蝗虫剑
- [ ] 各类变身器：Shot Riser和SlashRiser需要单体手持模型，所有腰带需要手持材质或模型，并且需要护甲模型。
————————————————————————————————
音效问题：
- [ ] 密钥启动音效
- [ ] Driver启动音效
- [ ] Riser启动音效
- [ ] 各种变身音效
- [ ] 武器攻击音（Shot Riser以及公文包枪，蝗虫剑的扳机音效）
- [ ] 各种必杀音效
- [ ] 卫星相关音效
- [ ] AI设备启动音（humagear module和zaiaspec的启动音）
————————————————————————————————
特效问题：
- [ ] 变身特效
- [ ] AI设备启动时HUD特效
- [ ] 武器特效
- [ ] 必杀特效

**Comment by 0999312** [comment]
模型错位问题：
目前腿部在移动时错位，其他地方目前暂时没有错位情况。

**Comment by 0999312** [comment]
代码问题追加：
- [ ] 材料/合成问题
- [ ] 能量流体/石油/燃油
- [ ] 与其他科技模组的联动
